import type { AgentId, AgentKind } from "../types.ts";

/** Hard limits keep hook-controlled text from becoming an unbounded paste. */
export const MAX_HANDOFF_MESSAGE_BYTES = 64 * 1024;
export const MAX_HANDOFF_PROMPT_BYTES = 32 * 1024;
export const MAX_HANDOFF_ACTION_BYTES = 16 * 1024;
export const MAX_HANDOFF_PACKET_BYTES = 128 * 1024;

export interface ObservedAgentMetadata {
  /** Values are last observed at or before the selected completion event. */
  model: string | null;
  effort: string | null;
  permissionMode: string | null;
  cwd: string | null;
  transcriptPath: string | null;
}

/** Stable, provider-neutral context extracted from one completed native turn. */
export interface CompletionContext {
  sourceAgent: AgentId;
  sourceKind: AgentKind;
  sourceSession: string;
  sourceEventId: number;
  completedAt: number;
  nativeType: string;
  prompt: string | null;
  promptId: string | null;
  turnId: string | null;
  lastAssistantMessage: string;
  observed: ObservedAgentMetadata;
}

/** Exact configured identity whose retained completion may be selected. */
export interface CompletionSourceSelector {
  agentId: AgentId;
  kind: AgentKind;
  sessionId: string;
}

export interface GitContext {
  available: boolean;
  root: string | null;
  head: string | null;
  branch: string | null;
  status: string;
  diffStat: string;
  changedPaths: string[];
  truncated: boolean;
  /** Stable machine-readable degradation reason; never raw git stderr. */
  reason: "not-a-git-repository" | "git-unavailable" | "git-command-failed" | null;
}

export const HANDOFF_RECEIPT_STATUSES = [
  "prepared",
  "approved",
  "delivering",
  "delivered",
  "acknowledged",
  "failed",
  "cancelled",
] as const;
export type HandoffReceiptStatus = (typeof HANDOFF_RECEIPT_STATUSES)[number];

export interface HandoffPacketInput {
  id: string;
  from: AgentId;
  to: AgentId;
  targetKind: AgentKind;
  sourceSession: string;
  targetSession: string | null;
  createdAt: string;
  completion: CompletionContext;
  git: GitContext;
  requestedAction: string;
}

export interface HandoffReceipt {
  version: 1;
  id: string;
  packetPath: string;
  /** SHA-256 of the exact UTF-8 packet bytes approved for delivery. */
  packetSha256: string;
  from: AgentId;
  to: AgentId;
  sourceKind: AgentKind;
  targetKind: AgentKind;
  sourceSession: string;
  targetSession: string | null;
  status: HandoffReceiptStatus;
  detail: string | null;
  /** Number of terminal delivery attempts begun for this packet. */
  attempt: number;
  createdAt: string;
  approvedAt: string | null;
  deliveryStartedAt: string | null;
  deliveredAt: string | null;
  /** Exact accepted target turn recorded durably before its reservation releases. */
  targetTurnEventId: number | null;
  targetPromptId: string | null;
  targetTurnId: string | null;
  targetTurnObservedAt: string | null;
  updatedAt: string;
}

export type HandoffReceiptIdentity = Pick<
  HandoffReceipt,
  | "version"
  | "id"
  | "packetPath"
  | "packetSha256"
  | "from"
  | "to"
  | "sourceKind"
  | "targetKind"
  | "sourceSession"
  | "createdAt"
>;

export interface CreateHandoffArtifactInput {
  repo: string;
  from: AgentId;
  to: AgentId;
  targetKind: AgentKind;
  sourceSession: string;
  targetSession?: string | null;
  completion: CompletionContext;
  requestedAction: string;
  /** Pre-collected context is useful to show/approve exactly what will be written. */
  git?: GitContext;
  /** Optional deterministic values for callers/tests; generated by default. */
  id?: string;
  createdAt?: string;
}

export interface HandoffArtifact {
  id: string;
  packetPath: string;
  receiptPath: string;
  /** Exactly the bytes stored in packetPath and later delivered to the TUI. */
  packet: string;
  receipt: HandoffReceipt;
}

export interface HandoffReceiptUpdate {
  status: HandoffReceiptStatus;
  targetSession?: string | null;
  detail?: string | null;
  targetTurnEventId?: number | null;
  targetPromptId?: string | null;
  targetTurnId?: string | null;
  targetTurnObservedAt?: string | null;
  updatedAt?: string;
}
